PREFIX ccf: <http://purl.org/ccf/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX hgnc: <http://identifiers.org/hgnc/>

SELECT ?anatomical_structure ?anatomical_structure_label ?donor ?donor_sex WHERE {
    ?tissue_block rdf:type ccf:tissue_block ;
        ccf:has_registration_location [ ccf:collides_with ?anatomical_structure ] ;
        ccf:comes_from ?donor .
    OPTIONAL { ?anatomical_structure rdfs:label ?anatomical_structure_label }
    OPTIONAL { ?donor ccf:has_biological_sex [ rdfs:label ?donor_sex ] }
}
ORDER BY ?anatomical_structure_label