PREFIX ccf: <http://purl.org/ccf/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX hgnc: <http://identifiers.org/hgnc/>

SELECT DISTINCT ?tissue_block ?donor ?donor_sex
FROM <https://purl.humanatlas.io/graph/ccf>
FROM <https://purl.humanatlas.io/ds-graph/hubmap>
WHERE {
    ?tissue_block rdf:type ccf:Sample ;
    ccf:has_registration_location [ ccf:collides_with ?anatomical_structure ] ;
        ccf:comes_from ?donor .
    ?donor ccf:sex ?donor_sex .
}
ORDER BY ?tissue_block
