PREFIX ccf: <http://purl.org/ccf/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX hgnc: <http://identifiers.org/hgnc/>

SELECT (count(?tissue_block) as ?tissue_block_count) ?anatomical_structure ?anatomical_structure_label
FROM <https://purl.humanatlas.io/graph/ccf>
FROM <https://purl.humanatlas.io/ds-graph/hubmap>
WHERE {
    ?tissue_block rdf:type ccf:Sample ;
        ccf:has_registration_location [ ccf:collides_with ?anatomical_structure ] .
    BIND(IRI(?anatomical_structure) as ?anatomical_structure_iri) .
    ?anatomical_structure_iri rdfs:label ?anatomical_structure_label
}
GROUP BY ?anatomical_structure ?anatomical_structure_label
ORDER BY ?anatomical_structure_label
